In [2]:
import pandas as pd
import os

In [3]:
sample_info = "/Users/anb/Desktop/sampleinfo2.tsv"

sample_info_df = pd.read_csv(
    sample_info, comment="#", header=0, sep='\t', low_memory=False
)

In [4]:
sample_info_df

,title,geo_accession,status,submission_date,last_update_date,type,channel_count,source_name_ch1,organism_ch1,characteristics_ch1,...,contact_phone,contact_institute,contact_address,contact_city,contact_state,contact_zip/postal_code,contact_country,supplementary_file,data_row_count,tissue type:ch1
0,AE17N,GSM573952,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,adjacent normal tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,2402765257,NCI,9609 Medical Center Dr.,Rockville,MD,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM573n...,22477,esophageal squamous cell carcinoma (ESCC)
1,AE18N,GSM573953,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,adjacent normal tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,2402765257,NCI,9609 Medical Center Dr.,Rockville,MD,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM573n...,22477,esophageal squamous cell carcinoma (ESCC)
2,AE19N,GSM573954,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,adjacent normal tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,2402765257,NCI,9609 Medical Center Dr.,Rockville,MD,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM573n...,22477,esophageal squamous cell carcinoma (ESCC)
3,AE20N,GSM573955,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,adjacent normal tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,2402765257,NCI,9609 Medical Center Dr.,Rockville,MD,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM573n...,22477,esophageal squamous cell carcinoma (ESCC)
4,AE21N,GSM573956,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,adjacent normal tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,2402765257,NCI,9609 Medical Center Dr.,Rockville,MD,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM573n...,22477,esophageal squamous cell carcinoma (ESCC)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,AE15T,GSM574049,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,tumor tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,2402765257,NCI,9609 Medical Center Dr.,Rockville,MD,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM574n...,22477,esophageal squamous cell carcinoma (ESCC)
98,AE10T,GSM574050,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,tumor tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,2402765257,NCI,9609 Medical Center Dr.,Rockville,MD,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM574n...,22477,esophageal squamous cell carcinoma (ESCC)
99,AE11T,GSM574051,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,tumor tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,2402765257,NCI,9609 Medical Center Dr.,Rockville,MD,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM574n...,22477,esophageal squamous cell carcinoma (ESCC)
100,AE13T,GSM574052,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,tumor tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,2402765257,NCI,9609 Medical Center Dr.,Rockville,MD,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM574n...,22477,esophageal squamous cell carcinoma (ESCC)
101,AE16T,GSM574053,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,tumor tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,2402765257,NCI,9609 Medical Center Dr.,Rockville,MD,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM574n...,22477,esophageal squamous cell carcinoma (ESCC)

In [5]:
group = pd.DataFrame()
group['sample'] = sample_info_df['title']
group['case'] = 0
group['ctrl'] = 0
group['group'] = 0

In [6]:
group.loc[group['sample'].str.contains("N")==True,'ctrl'] = 1
group.loc[group['sample'].str.contains("T")==True,'case'] = 1

group.loc[group['sample'].str.contains("N")==True,'group'] = "normal"
group.loc[group['sample'].str.contains("T")==True,'group'] = "tumour"

In [7]:
group

    sample  case  ctrl   group
0    AE17N     0     1  normal
1    AE18N     0     1  normal
2    AE19N     0     1  normal
3    AE20N     0     1  normal
4    AE21N     0     1  normal
..     ...   ...   ...     ...
97   AE15T     1     0  tumour
98   AE10T     1     0  tumour
99   AE11T     1     0  tumour
100  AE13T     1     0  tumour
101  AE16T     1     0  tumour

[102 rows x 4 columns]

In [8]:
group.loc[group['sample'].str.contains("AE01")==True]

   sample  case  ctrl   group
35  AE01N     0     1  normal
86  AE01T     1     0  tumour

In [9]:
group.sort_values('sample', axis=0, ascending=True, inplace=True)

In [10]:
group

   sample  case  ctrl   group
35  AE01N     0     1  normal
86  AE01T     1     0  tumour
40  AE02N     0     1  normal
91  AE02T     1     0  tumour
41  AE03N     0     1  normal
..    ...   ...   ...     ...
76  AE51T     1     0  tumour
31  AE52N     0     1  normal
82  AE52T     1     0  tumour
26  AE53N     0     1  normal
77  AE53T     1     0  tumour

[102 rows x 4 columns]

In [11]:
group.reset_index(inplace=True, drop=True)

In [12]:
group

    sample  case  ctrl   group
0    AE01N     0     1  normal
1    AE01T     1     0  tumour
2    AE02N     0     1  normal
3    AE02T     1     0  tumour
4    AE03N     0     1  normal
..     ...   ...   ...     ...
97   AE51T     1     0  tumour
98   AE52N     0     1  normal
99   AE52T     1     0  tumour
100  AE53N     0     1  normal
101  AE53T     1     0  tumour

[102 rows x 4 columns]

In [13]:
a=[(x+1) for x in range(113) for _ in range(2)]
b=pd.DataFrame(columns=['number'])
b['number'] = a
b.reset_index
b

     number
0         1
1         1
2         2
3         2
4         3
..      ...
221     111
222     112
223     112
224     113
225     113

[226 rows x 1 columns]

In [14]:
group['patient'] = b['number'].copy()

In [15]:
group

    sample  case  ctrl   group  patient
0    AE01N     0     1  normal        1
1    AE01T     1     0  tumour        1
2    AE02N     0     1  normal        2
3    AE02T     1     0  tumour        2
4    AE03N     0     1  normal        3
..     ...   ...   ...     ...      ...
97   AE51T     1     0  tumour       49
98   AE52N     0     1  normal       50
99   AE52T     1     0  tumour       50
100  AE53N     0     1  normal       51
101  AE53T     1     0  tumour       51

[102 rows x 5 columns]

In [16]:
sampleInfoCorrected = pd.merge(left=sample_info_df, right=group, how='left', left_on='title', right_on='sample')

In [17]:
sampleInfoCorrected

,title,geo_accession,status,submission_date,last_update_date,type,channel_count,source_name_ch1,organism_ch1,characteristics_ch1,...,contact_zip/postal_code,contact_country,supplementary_file,data_row_count,tissue type:ch1,sample,case,ctrl,group,patient
0,AE17N,GSM573952,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,adjacent normal tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM573n...,22477,esophageal squamous cell carcinoma (ESCC),AE17N,0,1,normal,17
1,AE18N,GSM573953,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,adjacent normal tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM573n...,22477,esophageal squamous cell carcinoma (ESCC),AE18N,0,1,normal,18
2,AE19N,GSM573954,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,adjacent normal tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM573n...,22477,esophageal squamous cell carcinoma (ESCC),AE19N,0,1,normal,19
3,AE20N,GSM573955,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,adjacent normal tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM573n...,22477,esophageal squamous cell carcinoma (ESCC),AE20N,0,1,normal,20
4,AE21N,GSM573956,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,adjacent normal tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM573n...,22477,esophageal squamous cell carcinoma (ESCC),AE21N,0,1,normal,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,AE15T,GSM574049,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,tumor tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM574n...,22477,esophageal squamous cell carcinoma (ESCC),AE15T,1,0,tumour,15
98,AE10T,GSM574050,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,tumor tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM574n...,22477,esophageal squamous cell carcinoma (ESCC),AE10T,1,0,tumour,10
99,AE11T,GSM574051,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,tumor tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM574n...,22477,esophageal squamous cell carcinoma (ESCC),AE11T,1,0,tumour,11
100,AE13T,GSM574052,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,tumor tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM574n...,22477,esophageal squamous cell carcinoma (ESCC),AE13T,1,0,tumour,13
101,AE16T,GSM574053,Public on Sep 01 2010,Aug 03 2010,Aug 03 2010,RNA,1,tumor tissue,Homo sapiens,tissue type: esophageal squamous cell carcinom...,...,20850,USA,ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM574n...,22477,esophageal squamous cell carcinoma (ESCC),AE16T,1,0,tumour,16

In [18]:
out_dir = "/Users/anb/Desktop/"

sampleInfoCorrected.to_csv(os.path.join(out_dir, "GSE23400_sampleinfoCorrected2.tsv"), sep='\t', index=False, header=True)