In [37]:
import os
import pandas as pd
import numpy as np

In [38]:
# DEG file

DEG_file = "/Users/anb/Documents/CMEB-Lab/ESCC-Drug-Repositioning/DR-escc-data/output/GSE23400//filtered_de_results_1fc_05pval.tsv"

DEGs = pd.read_csv(
    DEG_file, comment="#", header=0, sep='\t', low_memory=False
)

In [39]:
DEGs

,ID,Gene.Symbol,ENTREZ_GENE_ID,Gene.Title,RefSeq.Transcript.ID,logFC,AveExpr,t,P.Value,adj.P.Val,B
0,202311_s_at,COL1A1,1277,"collagen, type I, alpha 1",NM_000088 /// XM_005257058 /// XM_005257059 //...,2.989800,8.331677,16.888972,5.885295e-32,8.436570e-28,62.106006
1,219787_s_at,ECT2,1894,epithelial cell transforming 2,NM_001258315 /// NM_001258316 /// NM_018098 //...,2.112317,6.052091,16.595630,2.296755e-31,1.646199e-27,60.768417
2,201897_s_at,CKS1B,1163,CDC28 protein kinase regulatory subunit 1B,NM_001826 /// NR_024163,1.528879,8.943643,16.420626,5.201664e-31,2.485529e-27,59.965068
3,204023_at,RFC4,5984,"replication factor C (activator 1) 4, 37kDa",NM_002916 /// NM_181573,1.716516,7.733155,16.113056,2.208688e-30,7.915387e-27,58.543533
4,203417_at,MFAP2,4237,microfibrillar-associated protein 2,NM_001135247 /// NM_001135248 /// NM_002403 //...,1.691285,8.179160,15.954053,4.685839e-30,1.306103e-26,57.803857
...,...,...,...,...,...,...,...,...,...,...,...
667,214414_x_at,HBA1 /// HBA2,3039 /// 3040,"hemoglobin, alpha 1 /// hemoglobin, alpha 2",NM_000517 /// NM_000558,-1.001693,8.801867,-4.127611,7.279271e-05,1.931304e-04,0.814180
668,205623_at,ALDH3A1,218,"aldehyde dehydrogenase 3 family, member A1",NM_000691 /// NM_001135167 /// NM_001135168 //...,-1.297811,9.728792,-4.062514,9.279016e-05,2.411434e-04,0.583333
669,218002_s_at,CXCL14,9547,chemokine (C-X-C motif) ligand 14,NM_004887,1.038378,9.744706,3.977215,1.270588e-04,3.219138e-04,0.284915
670,202222_s_at,DES,1674,desmin,NM_001927,-1.180520,9.869055,-3.968929,1.309680e-04,3.309989e-04,0.256177
671,213796_at,SPRR1A,6698,small proline-rich protein 1A,NM_001199828 /// NM_005987,-1.106883,12.903510,-3.700626,3.416290e-04,7.968194e-04,-0.649925

In [40]:
DEGS_mini = DEGs[['Gene.Symbol', 'logFC', 'P.Value']]

In [41]:
DEGS_mini

       Gene.Symbol     logFC       P.Value
0           COL1A1  2.989800  5.885295e-32
1             ECT2  2.112317  2.296755e-31
2            CKS1B  1.528879  5.201664e-31
3             RFC4  1.716516  2.208688e-30
4            MFAP2  1.691285  4.685839e-30
..             ...       ...           ...
667  HBA1 /// HBA2 -1.001693  7.279271e-05
668        ALDH3A1 -1.297811  9.279016e-05
669         CXCL14  1.038378  1.270588e-04
670            DES -1.180520  1.309680e-04
671         SPRR1A -1.106883  3.416290e-04

[672 rows x 3 columns]

In [42]:
DEGS_mini['abslogfc'] = DEGS_mini['logFC'].abs()

/var/folders/_n/s_910cbn0dg5t1lpsjv2h90w0000gn/T/ipykernel_54157/4075167138.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DEGS_mini['abslogfc'] = DEGS_mini['logFC'].abs()

In [43]:
DEGS_mini

       Gene.Symbol     logFC       P.Value  abslogfc
0           COL1A1  2.989800  5.885295e-32  2.989800
1             ECT2  2.112317  2.296755e-31  2.112317
2            CKS1B  1.528879  5.201664e-31  1.528879
3             RFC4  1.716516  2.208688e-30  1.716516
4            MFAP2  1.691285  4.685839e-30  1.691285
..             ...       ...           ...       ...
667  HBA1 /// HBA2 -1.001693  7.279271e-05  1.001693
668        ALDH3A1 -1.297811  9.279016e-05  1.297811
669         CXCL14  1.038378  1.270588e-04  1.038378
670            DES -1.180520  1.309680e-04  1.180520
671         SPRR1A -1.106883  3.416290e-04  1.106883

[672 rows x 4 columns]

In [44]:
DEGS_mini.sort_values(['Gene.Symbol', 'abslogfc', 'P.Value'], ascending=False, inplace=True)
DEGS_mini.drop_duplicates(subset = ["Gene.Symbol"], inplace=True)

/var/folders/_n/s_910cbn0dg5t1lpsjv2h90w0000gn/T/ipykernel_54157/3332401329.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DEGS_mini.sort_values(['Gene.Symbol', 'abslogfc', 'P.Value'], ascending=False, inplace=True)
/var/folders/_n/s_910cbn0dg5t1lpsjv2h90w0000gn/T/ipykernel_54157/3332401329.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DEGS_mini.drop_duplicates(subset = ["Gene.Symbol"], inplace=True)

In [45]:
DEGS_mini.sort_values(['abslogfc', 'P.Value'], ascending=False, inplace=True)

/var/folders/_n/s_910cbn0dg5t1lpsjv2h90w0000gn/T/ipykernel_54157/2564628457.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DEGS_mini.sort_values(['abslogfc', 'P.Value'], ascending=False, inplace=True)

In [46]:
DEGS_mini

       Gene.Symbol     logFC       P.Value  abslogfc
6             MMP1  4.442564  8.645952e-29  4.442564
110         CRISP3 -4.246975  8.533328e-21  4.246975
143            MAL -3.968327  8.650061e-20  3.968327
298           CRNN -3.654040  3.309579e-16  3.654040
254           SCEL -3.496086  4.159160e-17  3.496086
..             ...       ...           ...       ...
637          ACKR3  1.007208  1.498846e-06  1.007208
201           COBL -1.004592  1.908805e-18  1.004592
541         HS3ST1 -1.001725  5.010626e-10  1.001725
667  HBA1 /// HBA2 -1.001693  7.279271e-05  1.001693
630           TNS1 -1.001215  6.067785e-07  1.001215

[522 rows x 4 columns]

In [47]:
DEGS_mini.reset_index(inplace=True,drop=True)

In [48]:
DEGS_mini_sort_pval = DEGS_mini.copy()
DEGS_mini_sort_pval.sort_values(['P.Value'], ascending=True, inplace=True)
DEGS_mini_sort_pval.reset_index(inplace=True,drop=True)

In [49]:
DEGS_mini_sort_pval

       Gene.Symbol     logFC       P.Value  abslogfc
0             ECT2  2.112317  2.296755e-31  2.112317
1            CKS1B  1.528879  5.201664e-31  1.528879
2             RFC4  1.716516  2.208688e-30  1.716516
3            MFAP2  1.691285  4.685839e-30  1.691285
4             MMP1  4.442564  8.645952e-29  4.442564
..             ...       ...           ...       ...
517          KRT14  1.321544  6.436790e-05  1.321544
518  HBA1 /// HBA2 -1.001693  7.279271e-05  1.001693
519        ALDH3A1 -1.297811  9.279016e-05  1.297811
520         CXCL14  1.038378  1.270588e-04  1.038378
521            DES -1.180520  1.309680e-04  1.180520

[522 rows x 4 columns]

In [50]:
DEGS_mini = DEGS_mini[['Gene.Symbol', 'logFC', 'P.Value']]

In [51]:
DEGS_mini

       Gene.Symbol     logFC       P.Value
0             MMP1  4.442564  8.645952e-29
1           CRISP3 -4.246975  8.533328e-21
2              MAL -3.968327  8.650061e-20
3             CRNN -3.654040  3.309579e-16
4             SCEL -3.496086  4.159160e-17
..             ...       ...           ...
517          ACKR3  1.007208  1.498846e-06
518           COBL -1.004592  1.908805e-18
519         HS3ST1 -1.001725  5.010626e-10
520  HBA1 /// HBA2 -1.001693  7.279271e-05
521           TNS1 -1.001215  6.067785e-07

[522 rows x 3 columns]

In [ ]:
DEGS_mini.head(20)

In [ ]:
DEGs_sorted_logfc_pval = DEGS_mini.copy()
DEGs_sorted_logfc_pval_top20 = DEGS_mini.head(20).copy()

In [54]:
out_dir = "/Users/anb/Documents/CMEB-Lab/ESCC-Drug-Repositioning/DR-escc-data/output/GSE23400/DEG-analysis"

DEGs_sorted_logfc_pval.to_csv(os.path.join(out_dir, "DEGs_sorted_logfc_pval.tsv"), sep='\t', index=False)
DEGs_sorted_logfc_pval['Gene.Symbol'].to_csv(os.path.join(out_dir, "DEGs_sorted_logfc_pval_genes.tsv"), sep='\t', index=False)

DEGS_mini_sort_pval.to_csv(os.path.join(out_dir, "DEGs_sorted_pval.tsv"), sep='\t', index=False)
DEGS_mini_sort_pval[['Gene.Symbol']].to_csv(os.path.join(out_dir, "DEGs_sorted_pval_genes.tsv"), sep='\t', index=False)



DEGs_sorted_logfc_pval_top20.to_csv(os.path.join(out_dir, "DEGs_sorted_logfc_pval_top20.tsv"), sep='\t', index=False)

In [ ]:
DEGs_sorted_logfc_pval_top20

In [ ]:
DEGs_sorted_logfc_pval[DEGs_sorted_logfc_pval['logFC'] > 0].head(30)

In [ ]:
DEGs_sorted_logfc_pval[DEGs_sorted_logfc_pval['logFC'] < 0].head(30)